@startuml
hide members
namespace ajb{
    namespace particles{
    }
    namespace equipment{
    }
    namespace analysis{
    }
    namespace miscellaneous{
    }
    namespace gui{
        class Window extends .javax.swing.JFrame
    }
    namespace tests{
        'namespace tdd{
        '}
        'namespace unit{
        '}
    }
}


!include Ebene2/2Ebene-Particles.puml

!include Ebene2/2Ebene-Analysis.puml

!include Ebene2/2Ebene-equipment.puml

!include Ebene2/2Ebene-miscellaneous.puml

!include Ebene2/Ebene3/3Ebene-equipment-SubstanceContainer.puml

!include Ebene2/Ebene3/3Ebene-parts-ExternalReagent.puml


@enduml