@startuml

namespace ajb.equipment{
        class Beaker extends SubstanceContainer

        class TestTube extends SubstanceContainer

        class ErlenmeyerFlask extends SubstanceContainer
}

@enduml