@startuml
!include ../2Ebene-Parts.puml
hide ajb.analysis
hide ajb.parts.ExternalReagent
hide ajb.parts.AbstractPart

namespace ajb.parts{
        class Beaker extends ProbeContainer

        class TestTube extends ProbeContainer

        class ErlenmeyerFlask extends ProbeContainer
}

@enduml