@startuml
!include ../2Ebene-equipment.puml
hide ajb.analysis
hide ajb.equipment.ExternalReagent
hide ajb.equipment.AbstractPart

namespace ajb.equipment{
        class Beaker extends SubstanceContainer

        class TestTube extends SubstanceContainer

        class ErlenmeyerFlask extends SubstanceContainer
}

@enduml