@startuml

namespace ajb.equipment{
    BunsenBurner .up.|> ExternalReagent
    Centrifuge .up.|> ExternalReagent
    BoilingStone .up.|> ExternalReagent
    Filter .up.|> ExternalReagent
'    AgingProcess .up.|> ExternalReagent
}

@enduml