@startuml
!include ../2Ebene-equipment.puml
hide ajb.analysis
hide ajb.equipment.SubstanceContainer
hide ajb.equipment.AbstractPart

namespace ajb.equipment{
    BunsenBurner .up.|> ExternalReagent
    Centrifuge .up.|> ExternalReagent
    BoilingStone .up.|> ExternalReagent
    Filter .up.|> ExternalReagent
'    AgingProcess .up.|> ExternalReagent
}

@enduml