@startuml

namespace ajb{
    namespace gui{
        class Window
    }
    namespace particles{
    }
    namespace equipment{
    }
    namespace analysis{
    }
    namespace miscellaneous{
    }
    namespace tests{
    }
}
!include Ebene2/2Ebene-Particles.puml
!include Ebene2/2Ebene-analysis.puml
!include Ebene2/2Ebene-equipment.puml

@enduml