@startuml

component AJB
actor Spieler
component HighscoreSpeicher
component Jackson
component ElementSpeicher

AJB -- "Leseoperation" HighscoreSpeicher
AJB --- "konvertiert JSON to Objects" Jackson
AJB ---- "Leseoperation" ElementSpeicher
AJB --- "Eingabesysteme" Spieler

@enduml