@startuml
!include 2Ebene-Analysis.puml

namespace ajb{
    namespace equipment {
        interface AbstractPart{
            +interact(Element Element)
        }

        interface ExternalReagent implements AbstractPart{
'            #countdown:Time
'            #state
        }
        ExternalReagent " # interactor" --> SubstanceContainer

        abstract class SubstanceContainer implements AbstractPart {
            # {final} maxVolume: double
            #currentVolume: double = 0
            +clear();
            +fill(Element element);
            +SubstanceContainer(double maxVolume)
        }
        SubstanceContainer " # substance" -up-> .ajb.analysis.Substance

    }
}

@enduml